# Generated by Django 2.2.15 on 2020-08-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Cattorec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Ingtorec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.AddField(
            model_name='ingtorec',
            name='Recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Recipe'),
        ),
        migrations.AddField(
            model_name='cattorec',
            name='Recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Recipe'),
        ),
    ]
