# Generated by Django 2.2.15 on 2020-08-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200810_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='static/app/images'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='loves',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='shortdescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
